import React, { useState } from 'react';
import { FaSearch, FaAngleLeft, FaAngleRight } from 'react-icons/fa';
import ReactPaginate from 'react-paginate';

const Home = () => {

    // Sample data for pagination
    const sampleData = [
        { id: 1, title: 'Title 1', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum arcu sit amet posuere vestibulum. Vivamus fermentum turpis nec erat scelerisque, vitae convallis leo lobortis. Proin at vehicula ante. Aliquam volutpat orci a est tincidunt facilisis. Sed convallis libero sed ' },
        { id: 2, title: 'Title 2', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at nisl nec lectus facilisis euismod. Suspendisse potenti. Nam viverra augue id justo finibus, auctor ultricies mauris vehicula. Donec vitae augue leo. Nam consectetur nibh nec orci fermentum, a dapibus ligula rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam quis sem eget sapien accumsan scelerisque. Nam eu nisi lacinia, semper eros eget, volutpat felis. Ut et enim in purus dignissim sollicitudin nec id ipsum. Sed hendrerit felis eget nulla sagittis vestibulum. Donec tempor tellus sit amet ultrices vestibulum.' },
        { id: 3, title: 'Title 3', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula justo nec sem ultricies, ac rutrum libero vehicula. Cras a mi eu mauris ultrices semper vitae ut purus. Ut et vehicula turpis. Suspendisse potenti. Sed hendrerit nulla vel mauris feugiat, vel aliquet ante accumsan. Aenean sit amet purus vel ipsum ultricies laoreet. Duis auctor, eros quis dictum vehicula, odio ligula feugiat velit, vel hendrerit nisi felis nec dui. Vivamus auctor magna ut sem pharetra, sed cursus ante posuere. Fusce ut ante eget lorem euismod gravida. Fusce quis odio eget quam tristique auctor nec ut nulla. Integer fringilla turpis a justo' },
        { id: 4, title: 'Title 4', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sodales velit at dapibus suscipit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed vitae risus sapien. Donec euismod volutpat purus, nec viverra justo ultrices eget. In efficitur ligula in massa fermentum, in gravida magna feugiat. Proin auctor, ex nec tristique consequat, neque nibh viverra turpis, a lobortis ligula est et purus. Cras ac felis ullamcorper, tempor mi nec, bibendum lorem. Morbi tempus felis ac sapien hendrerit, vel bibendum quam malesuada. Nulla facilisi. Cras elementum turpis vel nibh facilisis gravida. Duis volutpat diam id ' },
        { id: 5, title: 'Title 5', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 6, title: 'Title 6', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 7, title: 'Title 7', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 8, title: 'Title 8', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 9, title: 'Title 9', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 10, title: 'Title 10', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 11, title: 'Title 11', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 12, title: 'Title 12', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 13, title: 'Title 13', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 14, title: 'Title 14', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 15, title: 'Title 15', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 16, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 17, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 18, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 19, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 20, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 21, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 22, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 23, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 24, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 25, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
        { id: 26, title: 'Title 16', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, nunc eu rutrum ultricies, odio elit egestas dui, sed eleifend elit elit ut enim. Vestibulum dictum, velit nec sollicitudin pharetra, ipsum felis finibus nisi, id volutpat eros tortor in velit. Duis ut interdum magna. Maecenas malesuada nisi mi, id tincidunt lectus tempus nec. Proin nec neque id sem vehicula ullamcorper eu vel turpis. Curabitur ut neque vel justo volutpat ullamcorper in non mauris. Suspendisse eu tellus mauris. Mauris gravida sollicitudin lorem, vel tincidunt felis commodo nec. Sed condimentum, nunc auctor vestibulum ultricies, arcu quam commodo lectus, at ultrices magna tortor at ipsum. Donec auctor purus felis' },
    ];
    // Pagination state
    const [currentPage, setCurrentPage] = useState(0);
    const [totalResults, setTotalResults] = useState(sampleData.length);
    const itemsPerPage = 5;
    const pageCount = Math.ceil(sampleData.length / itemsPerPage);

    const handlePageChange = (selectedPage) => {
        setCurrentPage(selectedPage.selected);
    };

    // Current page data
    const offset = currentPage * itemsPerPage;
    const currentPageData = sampleData.slice(offset, offset + itemsPerPage);

    return (
        <div className="flex flex-col mt-2 text-black mx-auto w-full px-10 ">
            <h1 className="text-red-600 font-bold text-center text-2xl mb-2">Data Catalogue</h1>
            <div className="bg-white rounded-md shadow-lg px-4 py-2 flex items-center justify-between mb-8 mx-auto w-full">
                <input
                    type="text"
                    placeholder="Search Our Data Catalogue"
                    className="text-gray-800 flex-1 px-4 py-2 text-sm rounded-l-md w-full border outline-none"

                />
                <button className="bg-red-600 text-white px-4 py-2 rounded-r-md flex items-center justify-center">
                    <FaSearch size={20} style={{ verticalAlign: 'middle' }} /> {/* Adjust vertical alignment */}
                </button>
            </div>

            <div className="bg-white shadow-lg rounded-md mx-auto w-full  ">
                <div className="px-4 py-2 flex justify-end text-right">
                    <span>
                        Showing  {offset + currentPageData.length} of {totalResults} results
                    </span>
                </div>
                <div className='max-h-96  overflow-auto '>
                    {currentPageData.map((item, index) => (
                        <div key={index} className="px-4 py-2">
                            <h2 className="font-bold text-red-600">{item.title}</h2>
                            <p>{item.description}</p>
                            <div className="flex items-center mt-2">
                                <button className="bg-gray-200 text-gray-800 px-2 py-1 rounded-full">
                                    Format
                                </button>
                            </div>
                            <hr className="my-4" />
                        </div>
                    ))}
                </div>


{/* Pagination */}
<div className="pagination justify-center flex mt-4">
  <ReactPaginate
    previousLabel={<FaAngleLeft className="inline-block align-middle" />}
    nextLabel={<FaAngleRight className="inline-block align-middle" />}
    pageCount={pageCount}
    onPageChange={handlePageChange}
    containerClassName={'flex'}
    activeClassName={'active bg-gray-200 text-gray-800'}
    previousClassName={'pagination-prev border bg-white text-gray-800 px-4 py-2 shadow flex items-center justify-center'}
    nextClassName={'pagination-next bg-white border text-gray-800 px-4 py-2 shadow flex items-center justify-center'}
    disabledClassName={'pagination-disabled border opacity-50 cursor-not-allowed'}
    pageClassName={'page-item border text-gray-800 px-4 py-2 shadow'}
    breakClassName={'page-item border text-gray-400 px-4 py-2 font-bold'}
    breakLabel={'...'}
    marginPagesDisplayed={1}
    pageRangeDisplayed={3}
    renderOnZeroPageCount={null}
  />
</div>




                <hr className="my-4" />
            </div>


        </div>
    );
};

export default Home;
